const runtimeExternalPackageIncludes = [
  './node_modules/@datastructures-js/**/*',
  './node_modules/@ffprobe-installer/ffprobe/**/*',
  './node_modules/@livekit/**/*',
  './node_modules/@pinojs/**/*',
  './node_modules/@remotion/bundler/**/*',
  './node_modules/@remotion/renderer/**/*',
  './node_modules/@remotion/studio/**/*',
  './node_modules/@rspack/**/*',
  './node_modules/@runwayml/avatars-node-rpc/**/*',
  './node_modules/atomic-sleep/**/*',
  './node_modules/colorette/**/*',
  './node_modules/dateformat/**/*',
  './node_modules/esbuild/**/*',
  './node_modules/fast-copy/**/*',
  './node_modules/fast-safe-stringify/**/*',
  './node_modules/get-audio-duration/**/*',
  './node_modules/help-me/**/*',
  './node_modules/joycon/**/*',
  './node_modules/minimist/**/*',
  './node_modules/on-exit-leak-free/**/*',
  './node_modules/pino/**/*',
  './node_modules/pino-abstract-transport/**/*',
  './node_modules/pino-pretty/**/*',
  './node_modules/pino-std-serializers/**/*',
  './node_modules/process-warning/**/*',
  './node_modules/pump/**/*',
  './node_modules/quick-format-unescaped/**/*',
  './node_modules/real-require/**/*',
  './node_modules/remotion/**/*',
  './node_modules/safe-stable-stringify/**/*',
  './node_modules/secure-json-parse/**/*',
  './node_modules/sonic-boom/**/*',
  './node_modules/strip-json-comments/**/*',
  './node_modules/thread-stream/**/*',
  './src/remotion/**/*',
];

/** @type {import('next').NextConfig} */
const nextConfig = {
  allowedDevOrigins: ['127.0.0.1'],
  output: 'standalone',
  outputFileTracingRoot: __dirname,
  outputFileTracingIncludes: {
    '/api/avatar/session': runtimeExternalPackageIncludes,
    '/api/pipeline/*': runtimeExternalPackageIncludes,
  },
  serverExternalPackages: [
    'get-audio-duration',
    '@ffprobe-installer/ffprobe',
    '@remotion/bundler',
    '@remotion/renderer',
    '@runwayml/avatars-node-rpc',
    '@datastructures-js/deque',
    '@livekit/mutex',
    '@livekit/rtc-node',
    '@livekit/rtc-ffi-bindings',
    '@livekit/typed-emitter',
    '@pinojs/redact',
    'atomic-sleep',
    'colorette',
    'dateformat',
    'fast-copy',
    'fast-safe-stringify',
    'help-me',
    'joycon',
    'minimist',
    'on-exit-leak-free',
    'pino',
    'pino-abstract-transport',
    'pino-pretty',
    'pino-std-serializers',
    'process-warning',
    'pump',
    'quick-format-unescaped',
    'real-require',
    'safe-stable-stringify',
    'secure-json-parse',
    'sonic-boom',
    'strip-json-comments',
    'thread-stream',
  ],
};

module.exports = nextConfig;
