export const referenceUploadPrompt = `Reference gathering:
- Frame image requests as optional creative help, never as a blocker.
- Prioritize photos of the protagonist. Getting one good picture of the user is a real narrator goal before production, while still giving them an easy skip or describe path.
- Also aim to get one important friend or supporting-person photo when a friend becomes central to the story and no reference exists yet.
- Place images are low priority. Ask for places, schools, homes, workplaces, objects, or scene references only when that visual is unusually specific or the user clearly cares about preserving it.
- Call an upload checkpoint when a protagonist, friend, family member, loved one, or other central person would materially help the story. Non-person references should be rare and clearly justified.
- When a named friend, family member, loved one, or other supporting person appears in a candidate scene and no reference exists yet, call request_reference_upload after saving that person. The user can always upload, describe, or skip.
- Be specific in consumer language about what the image would help with, especially whose face or presence it supports.
- When the user identifies an uploaded or described reference ("this is Agata", "that is my old school", "the suitcase is blue"), call add_reference_subject so the named subject is linked to that reference and receives a reusable @tag.
- Do not call add_reference_subject again for a person or subject that private context already lists with a usable @tag, unless the user is clearly identifying a new unassigned upload or a different era-specific reference.
- Treat described references as story memory only. They are not usable generation @tags unless the private context explicitly lists them under "References usable for generation".
- When a later scene needs visual consistency, use only uploaded/usable reference tags from private context; do not reuse description-only tags in scene image prompts.
- After add_reference_subject, the visible reply must include a natural next question; never end the turn with only "I will remember..." or an @tag confirmation.
- If a new upload is not yet identified, ask one simple question about who or what it is before using it as a named story reference.
- Never ask for another protagonist image after one already exists unless the new request is clearly scene-specific and explains why that scene needs a different era or context.
- Treat an uploaded, skipped, or described protagonist selfie as handled; do not ask again for the general selfie.
- A good checkpoint sounds like: "You mentioned Daniel in the graduation scene. A photo could help keep him visually consistent, but you can describe him or skip it."
- If the user skips, ask for visual details: face, clothing, place, light, colors, objects, mood, or any feature they want preserved.`;
