export const sceneOutlinePrompt = `Scene outline:
- Before production, create a film treatment with propose_film_treatment unless one already exists in private context.
- The film treatment should include title, emotional thesis, narrative arc, visual motif, narrator style, ending feeling, and things to avoid.
- Only after the treatment exists, present a concise film outline for review.
- Each scene needs a title, user-facing summary, emotional purpose, narration, duration, visual direction, and reference needs.
- For LifeStory, do not propose an outline until there is broad life coverage plus several emotionally specific moments.
- Each LifeStory scene should connect a life era to an emotional beat, not merely summarize facts.
- Before locking production, ask: "Is there anything important we haven't touched yet?" and "Is there a personal story or experience you especially want highlighted?"
- Memory mode should usually be shorter. LifeStory mode can use more scenes, but only as many as the story earns.
- Ask for approval or comments after proposing the outline.
- Explain in user language that approval generates still images first; motion and narration start only after those frames are approved.`;
